import { QuoteContent, Category } from '../types';

// Seed quotes — displayed when the app is offline or as fallback content
export const SEED_QUOTES: QuoteContent[] = [
  {
    id: 'q1',
    type: 'quote',
    text: "The only way to do great work is to love what you do. If you haven't found it yet, keep looking. Don't settle.",
    author: 'Steve Jobs',
    categories: ['career'],
    createdAt: '2024-01-01',
  },
  {
    id: 'q2',
    type: 'quote',
    text: "You don't have to control your thoughts. You just have to stop letting them control you.",
    author: 'Dan Millman',
    categories: ['anxiety', 'self-love'],
    createdAt: '2024-01-01',
  },
  {
    id: 'q3',
    type: 'quote',
    text: 'The wound is the place where the Light enters you.',
    author: 'Rumi',
    categories: ['grief', 'spirituality', 'depression'],
    createdAt: '2024-01-01',
  },
  {
    id: 'q4',
    type: 'quote',
    text: "It does not matter how slowly you go as long as you do not stop.",
    author: 'Confucius',
    categories: ['career', 'fitness', 'student-life'],
    createdAt: '2024-01-01',
  },
  {
    id: 'q5',
    type: 'quote',
    text: "You yourself, as much as anybody in the entire universe, deserve your love and affection.",
    author: 'Buddha',
    categories: ['self-love', 'depression', 'relationships'],
    createdAt: '2024-01-01',
  },
  {
    id: 'q6',
    type: 'quote',
    text: "The comeback is always stronger than the setback.",
    author: 'Unknown',
    categories: ['addiction-recovery', 'fitness', 'career'],
    createdAt: '2024-01-01',
  },
  {
    id: 'q7',
    type: 'quote',
    text: "Financial freedom is available to those who learn about it and work for it.",
    author: 'Robert Kiyosaki',
    categories: ['financial'],
    createdAt: '2024-01-01',
  },
  {
    id: 'q8',
    type: 'quote',
    text: "Your children need your presence more than your presents.",
    author: 'Jesse Jackson',
    categories: ['parenting', 'relationships'],
    createdAt: '2024-01-01',
  },
  {
    id: 'q9',
    type: 'quote',
    text: "Education is the most powerful weapon which you can use to change the world.",
    author: 'Nelson Mandela',
    categories: ['student-life', 'career'],
    createdAt: '2024-01-01',
  },
  {
    id: 'q10',
    type: 'quote',
    text: "Inhale courage, exhale fear. You are stronger than you think.",
    author: 'Unknown',
    categories: ['anxiety', 'self-love'],
    createdAt: '2024-01-01',
  },
  {
    id: 'q11',
    type: 'quote',
    text: "Every morning brings new potential, but if you dwell on the misfortunes of the day before, you tend to overlook tremendous opportunities.",
    author: 'Harvey Mackay',
    categories: ['depression', 'career', 'self-love'],
    createdAt: '2024-01-01',
  },
  {
    id: 'q12',
    type: 'quote',
    text: "The best time to plant a tree was 20 years ago. The second best time is now.",
    author: 'Chinese Proverb',
    categories: ['financial', 'career', 'fitness'],
    createdAt: '2024-01-01',
  },
  {
    id: 'q13',
    type: 'quote',
    text: "What lies behind us and what lies before us are tiny matters compared to what lies within us.",
    author: 'Ralph Waldo Emerson',
    categories: ['self-love', 'spirituality'],
    createdAt: '2024-01-01',
  },
  {
    id: 'q14',
    type: 'quote',
    text: "Recovery is not a race. You don't have to feel guilty if it takes you longer than you thought it would.",
    author: 'Unknown',
    categories: ['addiction-recovery', 'grief', 'depression'],
    createdAt: '2024-01-01',
  },
  {
    id: 'q15',
    type: 'quote',
    text: "A healthy relationship will never require you to sacrifice your friends, your dreams, or your dignity.",
    author: 'Mandy Hale',
    categories: ['relationships', 'self-love'],
    createdAt: '2024-01-01',
  },
  {
    id: 'q16',
    type: 'quote',
    text: "Believe you can and you're halfway there.",
    author: 'Theodore Roosevelt',
    categories: ['career', 'student-life', 'fitness'],
    createdAt: '2024-01-01',
  },
  {
    id: 'q17',
    type: 'quote',
    text: "The greatest glory in living lies not in never falling, but in rising every time we fall.",
    author: 'Nelson Mandela',
    categories: ['addiction-recovery', 'depression', 'career'],
    createdAt: '2024-01-01',
  },
  {
    id: 'q18',
    type: 'quote',
    text: "You are never too old to set another goal or to dream a new dream.",
    author: 'C.S. Lewis',
    categories: ['career', 'self-love', 'financial'],
    createdAt: '2024-01-01',
  },
  {
    id: 'q19',
    type: 'quote',
    text: "Stars can't shine without darkness.",
    author: 'D.H. Sidebottom',
    categories: ['depression', 'grief', 'spirituality'],
    createdAt: '2024-01-01',
  },
  {
    id: 'q20',
    type: 'quote',
    text: "The struggle you're in today is developing the strength you need for tomorrow.",
    author: 'Robert Tew',
    categories: ['anxiety', 'fitness', 'student-life', 'career'],
    createdAt: '2024-01-01',
  },
];
