import { VideoContent } from '../types';

// Sample video data — in production, these would come from the YouTube API
// and Supabase content database. For the MVP, this serves as seed data.
export const SAMPLE_VIDEOS: VideoContent[] = [
  {
    id: 'v1',
    type: 'video',
    title: 'The Power of Morning Routines — How Successful People Start Their Day',
    description: 'Learn how building a consistent morning routine can transform your productivity and mindset.',
    thumbnailUrl: 'https://picsum.photos/seed/motivation1/400/225',
    videoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    sourceChannel: 'Motiversity',
    categories: ['career', 'self-love'],
    durationSeconds: 612,
    createdAt: '2024-01-15',
  },
  {
    id: 'v2',
    type: 'video',
    title: 'Overcoming Anxiety: You Are Not Your Thoughts',
    description: 'A powerful talk about understanding anxiety and learning to separate yourself from anxious thoughts.',
    thumbnailUrl: 'https://picsum.photos/seed/motivation2/400/225',
    videoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    sourceChannel: 'TEDx Talks',
    categories: ['anxiety', 'self-love'],
    durationSeconds: 780,
    createdAt: '2024-01-16',
  },
  {
    id: 'v3',
    type: 'video',
    title: "Discipline Equals Freedom — Jocko Willink's Guide to Getting Things Done",
    description: 'Why discipline is the ultimate path to freedom and success in every area of life.',
    thumbnailUrl: 'https://picsum.photos/seed/motivation3/400/225',
    videoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    sourceChannel: 'Goalcast',
    categories: ['career', 'fitness'],
    durationSeconds: 540,
    createdAt: '2024-01-17',
  },
  {
    id: 'v4',
    type: 'video',
    title: 'How to Love Yourself — Building Confidence from Within',
    description: 'Discover practical steps to build self-love and stop seeking validation from others.',
    thumbnailUrl: 'https://picsum.photos/seed/motivation4/400/225',
    videoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    sourceChannel: 'Jay Shetty',
    categories: ['self-love', 'relationships'],
    durationSeconds: 900,
    createdAt: '2024-01-18',
  },
  {
    id: 'v5',
    type: 'video',
    title: 'From Broke to Millionaire — The Financial Mindset Shift',
    description: 'How changing your relationship with money can transform your financial future.',
    thumbnailUrl: 'https://picsum.photos/seed/motivation5/400/225',
    videoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    sourceChannel: 'Motiversity',
    categories: ['financial', 'career'],
    durationSeconds: 720,
    createdAt: '2024-01-19',
  },
  {
    id: 'v6',
    type: 'video',
    title: 'Healing After Loss — Finding Hope in the Darkness',
    description: 'A compassionate guide to processing grief and finding a path forward.',
    thumbnailUrl: 'https://picsum.photos/seed/motivation6/400/225',
    videoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    sourceChannel: 'TEDx Talks',
    categories: ['grief', 'spirituality'],
    durationSeconds: 660,
    createdAt: '2024-01-20',
  },
  {
    id: 'v7',
    type: 'video',
    title: 'Student Success: Study Smarter, Not Harder',
    description: 'Science-backed study techniques that top students use to ace their exams.',
    thumbnailUrl: 'https://picsum.photos/seed/motivation7/400/225',
    videoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    sourceChannel: 'Thomas Frank',
    categories: ['student-life', 'career'],
    durationSeconds: 480,
    createdAt: '2024-01-21',
  },
  {
    id: 'v8',
    type: 'video',
    title: 'One Day at a Time — The Power of Recovery',
    description: 'Inspiring stories of people who overcame addiction and rebuilt their lives.',
    thumbnailUrl: 'https://picsum.photos/seed/motivation8/400/225',
    videoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    sourceChannel: 'Goalcast',
    categories: ['addiction-recovery', 'self-love'],
    durationSeconds: 840,
    createdAt: '2024-01-22',
  },
  {
    id: 'v9',
    type: 'video',
    title: 'Transform Your Body, Transform Your Mind',
    description: 'How physical fitness creates unstoppable mental resilience.',
    thumbnailUrl: 'https://picsum.photos/seed/motivation9/400/225',
    videoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    sourceChannel: 'Motiversity',
    categories: ['fitness', 'self-love'],
    durationSeconds: 570,
    createdAt: '2024-01-23',
  },
  {
    id: 'v10',
    type: 'video',
    title: 'The Art of Letting Go — Finding Peace in Relationships',
    description: 'Learn when to hold on and when to let go for healthier relationships.',
    thumbnailUrl: 'https://picsum.photos/seed/motivation10/400/225',
    videoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    sourceChannel: 'Jay Shetty',
    categories: ['relationships', 'self-love', 'spirituality'],
    durationSeconds: 690,
    createdAt: '2024-01-24',
  },
  {
    id: 'v11',
    type: 'video',
    title: 'Being the Parent Your Kids Need — Not the Perfect Parent',
    description: 'Why imperfection in parenting is a strength, not a weakness.',
    thumbnailUrl: 'https://picsum.photos/seed/motivation11/400/225',
    videoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    sourceChannel: 'TEDx Talks',
    categories: ['parenting', 'self-love'],
    durationSeconds: 750,
    createdAt: '2024-01-25',
  },
  {
    id: 'v12',
    type: 'video',
    title: 'When Depression Lies to You — Fighting Back with Truth',
    description: 'Understanding how depression distorts reality and tools to fight back.',
    thumbnailUrl: 'https://picsum.photos/seed/motivation12/400/225',
    videoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    sourceChannel: 'Goalcast',
    categories: ['depression', 'self-love', 'anxiety'],
    durationSeconds: 810,
    createdAt: '2024-01-26',
  },
];
